server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost/date_db
    username: root
    password: onetime
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet

